# Generated by Django 5.0.6 on 2024-06-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='task',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='task_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
