# Generated by Django 5.0.6 on 2024-06-24 07:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_alter_taskmanager_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='task_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
